name: vaultara
description: "A smart global expiry tracker for important documents."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core (required for all Firebase features)
  firebase_core: ^3.6.0

  # Optional (you will need these later if you want storage or database)
  # cloud_firestore: ^5.4.4
  # firebase_auth: ^5.2.0
  # firebase_storage: ^12.1.0

  # Native splash
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# ----------------------------------------------------
# Native splash screen configuration
# ----------------------------------------------------
flutter_native_splash:
  # Light mode splash
  color: "#F8F9FA"
  image: assets/images/vaultara_logo.png

  # Dark mode splash
  color_dark: "#003F5C"
  image_dark: assets/images/vaultara_logo.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#003F5C"
    image: assets/images/vaultara_logo.png
    color_dark: "#003F5C"
    image_dark: assets/images/vaultara_logo.png
