name: vaultara
description: "A smart global expiry tracker for important documents."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Native splash only
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# --- Native splash screen config ---
flutter_native_splash:
  # Light mode splash
  color: "#F8F9FA"
  image: assets/images/vaultara_logo.png

  # Dark mode (optional; fallback is light)
  color_dark: "#003F5C"
  image_dark: assets/images/vaultara_logo.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#003F5C"
    image: assets/images/vaultara_logo.png
    color_dark: "#003F5C"
    image_dark: assets/images/vaultara_logo.png
