name: vaultara
description: "A smart global expiry tracker for important documents."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.1.0

  flutter_native_splash: ^2.4.6
  flutter_tts: ^4.0.0

  local_auth: ^2.1.0
  shared_preferences: ^2.2.2

  url_launcher: ^6.3.0

  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart

flutter_native_splash:
  color: "#00897B"
  image: assets/images/vaultara_logo.png

  color_dark: "#00897B"
  image_dark: assets/images/vaultara_logo.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#00897B"
    image: assets/images/vaultara_logo.png
    color_dark: "#00897B"
    image_dark: assets/images/vaultara_logo.png
